/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_MyNDK */

#ifndef _Included_com_example_mama_tvoja_MyNDK
#define _Included_com_example_mama_tvoja_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mama_tvoja_MyNDK
 * Method:    calculate_temp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_mama_tvoja_MyNDK_calculate_temp
  (JNIEnv *, jobject, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
